#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: ""
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      username: 'xxxxxxxx'
      #password 密码
      password: 'xxxxxxxx'
      #address 地址，定位信息
      address: 中国xx省xx市 
      #email 接受通知消息的邮箱
      email: 
      #school 学校全称
      school: 河南牧业经济学院
      #lon 经度
      lon: 'xx.xxxxxx'
      #lat 纬度
      lat: 'xx.xxxxxx '
      #abnormalReason 反馈信息
      abnormalReason: 
      #photo 签到照片，不需要可不填，或者直接删除
      photo: 
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:
  #是否检查问题,true检查，false不检查
  check: false
  #附加信息组默认选项配置，没有可留空
  defaults:
#    表单默认选项配置，按顺序，注意，只有标必填项的才处理
#    - default:
##        表单项标题
#        title: 1、今日自己和家人体温是否正常？
#        #表单项默认值
#        value: 是
##        体温正常（<37.3℃）
#    - default:
#        title: 2、今天是否有跨市域移动？
#        value: 否
#    - default:
#        title: 3、今天是否去过中高风险地区？
#        value: 否
#    - default:
#        title: 4、今日是否完成阅读学院微信公众号推文任务？
#        value: 是

